orgs:
  opendatahub-io:
    admins:
    - accorvin
    - catrobson
    - cfchase
    - dchourasia
    - gmarkley-vi
    - jkoehler-redhat
    - LaVLaS
    - openshift-ci-robot
    - openshift-merge-robot
    - shgriffi
    - taneem-ibrahim
    default_repository_permission: read
    description: "Organization for Open Data Hub community"
    has_organization_projects: true
    has_repository_projects: true
    members:
    - 4n4nd
    - uidoyen
    - abhijeet-dhumal
    - adelton
    - AjayJagan
    - ajaypratap003
    - akchinSTC
    - alexcreasy
    - amadhusu
    - amsharma3
    - andrewballantyne
    - anishasthana
    - asanzgom
    - astefanutti
    - atheo89
    - Bobbins228
    - biswassri
    - carsonmh
    - christianvogt
    - ChristianZaccaria
    - cfullam1
    - chtyler
    - ChughShilpa
    - codeflare-machine-account
    - DaoDaoNoCode
    - danielezonca
    - devguyio
    - dfeddema
    - dgutride
    - DharmitD
    - dhirajsb
    - dlabaj
    - dibryant
    - diegolovison
    - dimakis
    - dpanshug
    - dtrifiro
    - durandom
    - erwangranger
    - etirelli
    - ezidav
    - fcami
    - Fiona-Waters
    - Gkrumbach07
    - gmfrasca
    - goern
    - grdryn
    - gregsheremeta
    - guimou
    - gzaronikas
    - harshad16
    - hbelmiro
    - heyselbi
    - HumairAK
    - israel-hdez
    - isinyaaa
    - jackdelahunt
    - jbusche
    - jbyrne-redhat
    - jedemo
    - jeff-phillips-18
    - jenny-s51
    - jeremyeder
    - jgarciao
    - jiripetrlik
    - Jooho
    - judyobrienie
    - jwforres
    - kaedward
    - keklundrh
    - KPostOffice
    - kywalker-rh
    - lampajr
    - ldimaggi
    - lucferbux
    - lugi0
    - manaswinidas
    - maroroman
    - Maxusmusti
    - MichaelClifford
    - mlassak
    - moulalis 
    - piotrpdev
    - pnaik1
    - ppadti
    - Raghul-M
    - ralombar
    - rareddy
    - r00ta
    - rimolive
    - riprasad
    - rkpattnaik780
    - RobGeada
    - romeokienzler
    - rpancham
    - ruivieira
    - sesheta
    - simrandhaliw
    - shawkins
    - spolti
    - Srihari1192
    - steventobin
    - sutaakar
    - tarilabs
    - tedhtchang
    - tteofili
    - VaishnaviHire
    - VanillaSpoon
    - VannTen
    - vconzola
    - VedantMahabaleshwarkar
    - VaniHaripriya
    - Xaenalt
    - xianli123
    - bartoszmajsak
    - cam-garrison
    - InnocentK
    - aslakknutsen
    - yannnz
    - yih-wang
    - ykaliuta
    - vaibhavjainwiz
    - winklerm
    - zdtsw
    members_can_create_repositories: false
    name: Open Data Hub
    teams:
      odh-manifests repository Admin:
        description: "Users with Admin access to the odh-manifests repo"
        maintainers:
        - LaVLaS
        - VaishnaviHire
        privacy: closed
        repos:
          odh-manifests: admin
      odh-manifests repository Contributors:
        description: "Users with Maintain access to the odh-manifests repo"
        maintainers:
        - LaVLaS
        - VaishnaviHire
        members:
        - AjayJagan
        - ajaypratap003
        - harshad16
        privacy: closed
        repos:
          odh-manifests: maintain
      odh-manifests repository Triage:
        description: "Users with Triage access to the odh-manifests repo"
        maintainers:
        - LaVLaS
        - VaishnaviHire
        members:
        - ajaypratap003
        privacy: closed
        repos:
          odh-manifests: triage
      Data Science Pipelines Maintainers:
        description: "Maintainers for ODH DSP and related repos."
        maintainers:
        - gregsheremeta
        - HumairAK
        members:
        - amadhusu
        - DharmitD
        - gmfrasca
        - hbelmiro
        - rimolive
        - VaniHaripriya
        privacy: closed
        repos:
          data-science-pipelines-operator: admin
          data-science-pipelines: admin
      Distributed Workloads Maintainers:
        description: ""
        maintainers:
        - accorvin
        - anishasthana
        - astefanutti
        - codeflare-machine-account
        - dimakis
        members:
        - abhijeet-dhumal
        - amsharma3
        - Bobbins228
        - ChristianZaccaria
        - ChughShilpa
        - Fiona-Waters
        - jiripetrlik
        - KPostOffice
        - Maxusmusti
        - MichaelClifford
        - Raghul-M
        - Srihari1192
        - sutaakar
        - tedhtchang
        - VanillaSpoon
        - winklerm
        privacy: closed
        repos:
          distributed-workloads: maintain
          kuberay: maintain
      Distributed Workloads Owners:
        description: ""
        maintainers:
        - accorvin
        - anishasthana
        members:
        - astefanutti
        - dimakis
        - sutaakar
        privacy: closed
        repos:
          distributed-workloads: admin
          kuberay: admin
      Elyra Maintainers:
        description: Maintainers of the Elyra AI notebook and build pipelines
        maintainers:
        - LaVLaS
        - romeokienzler
        - harshad16
        members:
        - akchinSTC
        privacy: closed
        repos:
          s2i-lab-elyra: maintain
      Model Registry Maintainers:
        description: "Maintainers for Model Registry related repos."
        maintainers:
        - dhirajsb
        - isinyaaa
        - lampajr
        - rareddy
        - tarilabs
        members:
        - shawkins
        privacy: closed
        repos:
          model-registry: admin
          model-registry-operator: admin
      Model Serving Maintainers:
        description: "Maintainers for Model Serving related repos."
        maintainers:
        - danielezonca
        - heyselbi
        - Jooho
        - taneem-ibrahim
        - Xaenalt
        members:
        - dtrifiro
        - israel-hdez
        - rpancham
        - spolti
        - vaibhavjainwiz
        - VedantMahabaleshwarkar
        privacy: closed
        repos:
          caikit: admin
          caikit-nlp: admin
          caikit-tgis-backend: admin
          caikit-tgis-serving: admin
          kserve: admin
          modelmesh: admin
          modelmesh-runtime-adapter: admin
          modelmesh-serving: admin
          odh-model-controller: admin
          opendatahub-community: triage
          openvino_model_server: admin
          rest-proxy: admin
          text-generation-inference: admin
      Notebook Maintainers:
        description: Maintainers of the notebook controller and all connected repos
        maintainers:
        - LaVLaS
        - harshad16
        - atheo89
        privacy: closed
        repos:
          kubeflow: admin
          notebooks: admin
      Notebook Devs:
        description: Members with triage access to repos maintained by the Notebook
          contributors
        maintainers:
        - LaVLaS
        - harshad16
        members:
        - atheo89
        - dibryant
        - mlassak
        - rkpattnaik780
        privacy: closed
        repos:
          kubeflow: triage
          notebooks: triage
      ODH Dashboard UX:
        description: UX team working on the ODH Dashboard component
        maintainers:
        - andrewballantyne
        - dgutride
        - kywalker-rh
        members:
        - cfullam1
        - kaedward
        - ralombar
        - simrandhaliw
        - vconzola
        - xianli123
        - yannnz
        - yih-wang
        privacy: closed
        repos:
          odh-dashboard: maintain
      ODH Dashboard Developers:
        description: Contributors to Dashboard
        maintainers:
        - andrewballantyne
        - dgutride
        - jkoehler-redhat
        members:
        - anishasthana
        - jenny-s51
        privacy: closed
        repos:
          odh-dashboard: write
      ODH Dashboard Maintainers:
        description: Maintainers of the ODH Dashboard repo
        maintainers:
        - andrewballantyne
        - cfchase
        - dgutride
        - LaVLaS
        members:
        - DaoDaoNoCode
        - dpanshug
        - Gkrumbach07
        - manaswinidas
        - pnaik1
        - ppadti
        - uidoyen
        privacy: closed
        repos:
          odh-dashboard: maintain
      ODH Dashboard Owners:
        description: Dashboard Owners
        maintainers:
        - andrewballantyne
        - dgutride
        - jkoehler-redhat
        members:
        - alexcreasy
        - christianvogt
        - lucferbux
        privacy: closed
        repos:
          odh-dashboard: admin
      ODH Documentatation Maintainers:
        description: Members responsible for the official ODH Document
        maintainers:
        - LaVLaS
        members:
        - jbyrne-redhat
        - chtyler
        privacy: closed
        repos:
          opendatahub-documentation: admin
      ODH Operator Maintainers:
        description: Maintainers of the ODH Operator repo
        maintainers:
        - ajaypratap003
        - etirelli
        - LaVLaS
        - VaishnaviHire
        - zdtsw
        members:
        - AjayJagan        
        privacy: closed
        repos:
          opendatahub-operator: admin
      ODH Community Maintainers:
        description: Maintainers of the ODH Community repo
        maintainers:
          - etirelli
          - jkoehler-redhat
          - LaVLaS
        members:
          - andrewballantyne
          - anishasthana
          - dgutride
          - heyselbi
          - jedemo
          - keklundrh
          - kywalker-rh
          - RobGeada
          - VaishnaviHire
        privacy: closed
        repos:
          opendatahub-community: maintain
      ODH Org Admin:
        description: Administrators of the ODH org. Members have all permissions.
        maintainers:
        - cfchase
        - LaVLaS
        - accorvin
        - shgriffi
        - jkoehler-redhat
        privacy: closed
        repos:
          .github: admin
          Fraud-Detection-with-Business-Workflows-Tutorial: admin
          architecture-decision-records: admin
          data-engineering-and-machine-learning-workshop: admin
          data-science-pipelines: admin
          data-science-pipelines-operator: admin
          distributed-workloads: admin
          kubeflow: admin
          landscapeapp: admin
          manifests: admin
          modelmesh: admin
          modelmesh-runtime-adapter: admin
          modelmesh-serving: admin
          odh-dashboard: admin
          odh-images: admin
          odh-landscape: admin
          odh-manifests: admin
          odh-s2i-project-cds: admin
          odh-s2i-project-cookiecutter: admin
          odh-s2i-project-simple: admin
          odh-template-sig: admin
          opendatahub-community: admin
          opendatahub-operator: admin
          opendatahub.io: admin
          opendatahub.io-redirects: admin
          rest-proxy: admin
          s2i-lab-elyra: admin
          testing-notebooks: admin
      SIG ML Developer Experience:
        description: Chairs of the ML Developer Experience SIG
        maintainers:
        - andrewballantyne
        - harshad16
        - kywalker-rh
        - LaVLaS
        privacy: closed
        repos:
          sig-ml-developer-experience: admin
      SIG Platform:
        description: Chairs of the Platform SIG
        maintainers:
          - LaVLaS
          - VaishnaviHire
          - taneem-ibrahim
          - jkoehler-redhat
          - zdtsw
        privacy: closed
        repos:
          sig-platform: admin
      SIG MLOps:
        description: The Chairs of the ML Ops SIG
        maintainers:
        - LaVLaS
        - anishasthana
        privacy: closed
        repos:
          data-science-pipelines: admin
          data-science-pipelines-operator: admin
          modelmesh: maintain
          modelmesh-runtime-adapter: maintain
          modelmesh-serving: admin
          odh-model-controller: admin
          rest-proxy: maintain
      adr-maintainers:
        description: Maintainers of the ADR repository
        maintainers:
        - etirelli
        - gregsheremeta
        - jeremyeder
        - jwforres
        - LaVLaS
        privacy: closed
        repos:
          architecture-decision-records: admin
      opendatahub.io Admins:
        description: Users with Admin access to the opendatahub.io and associated
          repos
        maintainers:
        - LaVLaS
        - VaishnaviHire
        members:
        - Gkrumbach07
        privacy: closed
        repos:
          opendatahub.io: admin
      opendatahub.io Triage:
        description: Users with access to Triage opendatahub.io issues
        maintainers:
        - LaVLaS
        members:
        - ezidav
        - VaishnaviHire
        privacy: closed
        repos:
          opendatahub.io: triage
      Service Mesh Integration:
        description: Users with access to repos required to develop/maintain Service Mesh related features
        maintainers:
        - aslakknutsen
        members:
        - bartoszmajsak
        - cam-garrison
        - InnocentK
        - israel-hdez
        privacy: closed
        repos:
          odh-dashboard: write
          odh-manifests: write
          odh-model-controller: write
          opendatahub-operator: write
          modelmesh-serving: write
      ODH Org Management Maintainers:
        description: Maintainers of the ODH Org Management repo
        maintainers:
          - accorvin
          - anishasthana
          - jkoehler-redhat
          - LaVLaS
          - VaishnaviHire
        privacy: closed
        repos:
          org-management: admin
      AI Edge Maintainers:
        description: Maintainers of the AI Edge Repo
        maintainers:
          - LaVLaS
          - devguyio
        members:
          - adelton
          - biswassri
          - grdryn
          - gzaronikas
          - israel-hdez
          - jackdelahunt  
          - piotrpdev
          - steventobin
        privacy: closed
        repos:
          ai-edge: write
      AI Edge Admins:
        description: Admins of the AI Edge Repo
        maintainers:
          - LaVLaS
          - devguyio
        privacy: closed
        repos:
          ai-edge: admin
